=== urban-tep/API/source/processingservices/bc/urban-tep-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="descriptor"
           targetNamespace="http://urban-tep.eo.esa.int/schema/urban-tep-schema.xsd"
           xmlns="http://urban-tep.eo.esa.int/schema/urban-tep-schema.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="qualified"
           elementFormDefault="qualified">
  <xs:element name="descriptor">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="processor">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="executable" type="xs:string" />
              <xs:element name="title" type="xs:string" />
              <xs:element name="description" type="xs:string" minOccurs="0" />
              <xs:element name="inputTypes" type="xs:string" minOccurs="0" />
              <xs:element name="outputType" type="xs:string" minOccurs="0" />
              <xs:element name="parameters">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" />
                          <xs:element name="type" type="xs:string" minOccurs="0" />
                          <xs:element name="description" type="xs:string" minOccurs="0" />
                          <xs:element name="default" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="packaging" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string" />
                    <xs:element name="version" type="xs:string" />
                    <xs:element name="type" type="xs:string" minOccurs="0" />
                    <xs:element name="dependencies" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="dependency" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="name" type="xs:string" />
                                <xs:element name="version" type="xs:string" minOccurs="0" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="resources" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="resource" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="name" type="xs:string" />
                                <xs:element name="value" type="xs:string" minOccurs="0" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== urban-tep/API/source/development/descriptor.xml
<?xml version="1.0" encoding="utf-8"?>
<utep:descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xmlns:utep="http://urban-tep.eo.esa.int/schema/urban-tep-schema.xsd"
                 xsi:schemaLocation="http://urban-tep.eo.esa.int/schema/urban-tep-schema.xsd urban-tep-schema.xsd">
  <utep:processor>
    <utep:name>Fmask8</utep:name>
    <utep:executable>fmask-and-merge.sh</utep:executable>
    <utep:title>Urban TEP Fmask for Landsat 8</utep:title>
    <utep:description><p>Performs cloud detection for Landsat 8 L1 products.</p></utep:description>
    <utep:inputTypes>Landsat8</utep:inputTypes>
    <utep:parameters>
      <utep:parameter>
        <utep:name>threshold</utep:name>
        <utep:type>string</utep:type>
        <utep:description>cloud probability threshold</utep:description>
        <utep:default>0.2</utep:default>
      </utep:parameter>
    </utep:parameters>
    <utep:packaging>
      <utep:name>fmask</utep:name>
      <utep:version>3.2</utep:version>
      <utep:type>Docker</utep:type>
      <utep:dependencies>
        <utep:dependency>
          <utep:name>snap</utep:name>
        </utep:dependency>
        <utep:dependency>
          <utep:name>mcr_root</utep:name>
          <utep:version>v81</utep:version>
        </utep:dependency>
      </utep:dependencies>
      <utep:resources>
        <utep:resource>
          <utep:name>memory</utep:name>
          <utep:value>7000</utep:value>
        </utep:resource>
        <utep:resource>
          <utep:name>timelimit</utep:name>
          <utep:value>3600</utep:value>
        </utep:resource>
      </utep:resources>
    </utep:packaging>
  </utep:processor>
</utep:descriptor>
